In [8]:
# Task 1
import numpy as np

arr = (3, 3)
arr = np.full(arr, 55)
arr

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [9]:
# Task 2
# Create a null vector of size 10 but the fifth value which is 1
import numpy as np

arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
# Task 3
# Reverse a vector
import numpy as np

arr = np.arange(10)
arr = arr[::-1]
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
# Task 4
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# Task 5
# Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np

arr = np.zeros([5, 5])
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [39]:
# Task 6
# Create a 3D array with zeros along the second axis 
import numpy as np

#ouput: [[[0. 0. 0. 0], [2,2,2,2], [0,0,0,0]], [[0,0,0,0], [2,2,2,2], [0,0,0,0]]]
arr = np.zeros([2, 3, 4])
arr[:, 1, :] = 2
print(arr)

[[[0. 0. 0. 0.]
  [2. 2. 2. 2.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [2. 2. 2. 2.]
  [0. 0. 0. 0.]]]


In [19]:
# Task 7
# Given the following two array, add them
import numpy as np

array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newRow = np.array([2, 1, 8])

arr = np.vstack([array, newRow])
print(arr)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [24]:
# Task 8
# Given the following array, calculate ((A+B)*(-A/2))
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2

result1 = np.add(A, B)
result2 = np.divide(-A, 2)
result = np.multiply(result1, result2)
result

array([-1.5, -1.5, -1.5])

In [26]:
# Task 9
# calculate mean of each row of the list
import numpy as np
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

for row in list:
    print(np.mean(row))

5.5
30.6
34.0


In [34]:
# Task 10
# how to print the following pattern of nxn using numpy
import numpy as np

arr = np.zeros([8, 8])
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
